######################################################################
# Automatically generated by qmake (3.0) Mon Oct 31 21:01:27 2016
######################################################################

TEMPLATE = app
TARGET = streamviewer
INCLUDEPATH += .
CONFIG += c++11

QT += multimedia multimediawidgets

HEADERS = streamviewer.h

SOURCES = streamviewer.cpp main.cpp
