######################################################################
# Automatically generated by qmake (3.0) Mon Oct 31 21:01:27 2016
######################################################################

TEMPLATE = app
TARGET = streamgrid
INCLUDEPATH += .
QT += multimedia multimediawidgets

HEADERS = streamgrid.h

SOURCES = streamgrid.cpp main.cpp
